apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-nodejs
  template:
    metadata:
      labels:
        app: crud-nodejs
    spec:
      containers:
        - name: app
          image: febriyanadji/crud-nodejs
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "128m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crud-nodejs-creds
                  key: db_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-nodejs-creds
                  key: db_password
            - name: MONGODB_DBNAME
              value: "crud-nodejs"
            - name: MONGODB_HOST
              value: mongo-svc
            - name: MONGODB_PORT
              value: "27017"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crud-nodejs-creds
                  key: jwt_secret
