apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-nodejs
spec:
  selector:
    matchLabels:
      app: crud-nodejs
  template:
    metadata:
      labels:
        app: crud-nodejs
    spec:
      containers:
        - name: app
          image: febriyanadji/crud-nodejs
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USERNAME
              value: "adminuser"
            - name: MONGODB_PASSWORD
              value: "password123"
            - name: MONGODB_HOST
              value: mongo-svc
            - name: MONGODB_PORT
              value: "27017"
            - name: JWT_SECRET
              value: "80ae4771c1728065a70f0bca20c1bb2604ddeaae26138eff0663f911bd24ca19"
