apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-nodejs
spec:
  selector:
    matchLabels:
      app: crud-nodejs
  template:
    metadata:
      labels:
        app: crud-nodejs
    spec:
      containers:
        - name: app
          image: febriyanadji/crud-nodejs
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USERNAME
              value: "adminuser"
            - name: MONGODB_PASSWORD
              value: "password123"
            - name: MONGODB_HOST
              value: "mongo-svc"

---
apiVersion: v1
kind: Service
metadata:
  name: crud-nodejs
spec:
  type: LoadBalancer
  selector:
    app: crud-nodejs
  ports:
    - port: 80
      targetPort: 3000
