resources:
  - namespace.yaml
  - mongodb-pvc.yaml
  - mongodb-secret.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - app-secret.yaml
  - app-deployment.yaml
  - app-service.yaml
namespace: crud-nodejs
