name: Build and Deploy to GKE
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t "febriyanadji/crud-nodejs:$GITHUB_SHA" .
      - name: push docker image
        run: docker push "febriyanadji/crud-nodejs:$GITHUB_SHA"
      # deploy-to-production:
      #   runs-on: ubuntu-latest
      #   steps:
      #     - name: Check out repository code
      #       uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      # - run: gcloud --quiet auth configure docker
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: my-cluster
          location: asia-southeast2-a
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: deploy to cluster
        run: |-
          cd ./kubernetes
          kustomize edit set image febriyanadji/crud-nodejs="febriyanadji/crud-nodejs:$GITHUB_SHA"
          kustomize build . | kubectl apply -f -
