name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t febriyanadji/crud-nodejs:latest .
      - name: push docker image
        run: docker push febriyanadji/crud-nodejs:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: deploy to cluster
        run: kustomize build ./kubernetes | kubectl apply -f -
