name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t febriyanadji/crud-nodejs:latest .
      - name: push docker image
        run: docker push febriyanadji/crud-nodejs:latest
      - name: kubectl
        run: kustomize
