name: Build and Deploy to GKE
on:
  push:
    branches:
      - master
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: login to dockerhub registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t febriyanadji/crud-nodejs:latest .
      - name: push docker image
        run: docker push febriyanadji/crud-nodejs:latest
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: deploy to cluster
        run: kustomize build ./kubernetes | kubectl apply -f -
